'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { CalendarDays, CircleGauge, Plus, Search, X } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Project={id:string;title:string;description:string|null;status:string;budget:number|null;currency:string;deadline:string|null;assigned_to:string|null;health_score:number|null;risk_level:string|null;created_at:string}
const statuses=['all','planned','active','on_hold','completed','cancelled']
const labels:Record<string,string>={all:'كل الحالات',planned:'مخطط',active:'نشط',on_hold:'متوقف',completed:'مكتمل',cancelled:'ملغي'}

export default function ProjectsPage(){
  const [rows,setRows]=useState<Project[]>([])
  const [query,setQuery]=useState('')
  const [status,setStatus]=useState('all')
  const [open,setOpen]=useState(false)
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')

  async function load(){setLoading(true);const sb=createClient();let q=sb.from('projects').select('id,title,description,status,budget,currency,deadline,assigned_to,health_score,risk_level,created_at').order('created_at',{ascending:false}).limit(200);if(status!=='all')q=q.eq('status',status);const {data,error}=await q;if(error)setError(error.message);else{setRows((data||[]) as Project[]);setError('')}setLoading(false)}
  useEffect(()=>{load()},[status])
  const filtered=useMemo(()=>{const n=query.trim().toLowerCase();if(!n)return rows;return rows.filter(r=>[r.title,r.description,r.status,r.risk_level].some(v=>String(v||'').toLowerCase().includes(n)))},[rows,query])

  async function createProject(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const sb=createClient();const {data:{user}}=await sb.auth.getUser();const payload={title:String(fd.get('title')||'').trim(),description:String(fd.get('description')||'').trim()||null,status:String(fd.get('status')||'planned'),budget:Number(fd.get('budget')||0)||null,currency:String(fd.get('currency')||'USD'),deadline:String(fd.get('deadline')||'')||null,created_by:user?.id||null};const {error}=await sb.from('projects').insert(payload);if(error)return setError(error.message);setOpen(false);await load()}

  return <div className="mx-auto max-w-[1500px] space-y-5">
    <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-card md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow">PROJECT DELIVERY</div><h2 className="mt-5 text-3xl font-black md:text-4xl">المشاريع</h2><p className="mt-3 text-sm leading-7 text-slate-500">كل مشروع يظهر من جدول projects الحالي مع الحالة، الميزانية، الموعد وصحة المشروع.</p></div><button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={17}/> مشروع جديد</button></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['الإجمالي',rows.length],['نشطة',rows.filter(r=>r.status==='active').length],['مكتملة',rows.filter(r=>r.status==='completed').length],['عالية المخاطر',rows.filter(r=>String(r.risk_level||'').toLowerCase()==='high').length]].map(([l,v])=><article key={String(l)} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-card"><strong className="font-[var(--font-inter)] text-3xl font-black">{v}</strong><span className="mt-2 block text-xs font-bold text-slate-400">{l}</span></article>)}</section>
    <section className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-card"><div className="flex flex-col gap-3 md:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4"><Search size={17} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-11 w-full bg-transparent outline-none" placeholder="بحث بالمشروع…"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold outline-none">{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div></section>
    {error&&<div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{loading?<div className="col-span-full p-10 text-center text-sm font-bold text-slate-400">جاري تحميل المشاريع…</div>:filtered.length?filtered.map(p=><article key={p.id} className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-card"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-black text-[#0071e3]">{labels[p.status]||p.status}</span><h3 className="mt-4 text-xl font-black">{p.title}</h3></div><div className="grid h-11 w-11 place-items-center rounded-xl bg-slate-50 text-slate-500"><CircleGauge size={20}/></div></div><p className="mt-3 min-h-14 text-sm leading-7 text-slate-500">{p.description||'بدون وصف.'}</p><div className="mt-6 grid grid-cols-2 gap-3 border-t border-slate-100 pt-4"><div><span className="block text-[10px] font-black text-slate-400">BUDGET</span><strong className="mt-1 block font-[var(--font-inter)]">{p.budget!=null?`${p.currency} ${Number(p.budget).toLocaleString()}`:'—'}</strong></div><div><span className="block text-[10px] font-black text-slate-400">DEADLINE</span><strong className="mt-1 flex items-center gap-1 text-sm"><CalendarDays size={14}/>{p.deadline||'—'}</strong></div></div>{p.health_score!=null&&<div className="mt-4"><div className="mb-2 flex justify-between text-[10px] font-black text-slate-400"><span>HEALTH</span><span>{p.health_score}%</span></div><div className="h-2 rounded-full bg-slate-100"><i style={{width:`${Math.min(100,Math.max(0,p.health_score))}%`}} className="block h-full rounded-full bg-emerald-500"/></div></div>}</article>):<div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm font-bold text-slate-400">لا توجد مشاريع.</div>}</section>
    {open&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/25 p-4 backdrop-blur-sm"><form onSubmit={createProject} className="w-full max-w-2xl rounded-[30px] border border-slate-200 bg-white p-6 shadow-soft md:p-8"><div className="flex items-start justify-between"><div><div className="eyebrow">NEW PROJECT</div><h3 className="mt-4 text-2xl font-black">إنشاء مشروع</h3></div><button type="button" onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><X size={18}/></button></div><div className="mt-7 grid gap-4 md:grid-cols-2"><label className="md:col-span-2"><span className="mb-2 block text-sm font-extrabold">اسم المشروع</span><input name="title" required className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none"/></label><label><span className="mb-2 block text-sm font-extrabold">الحالة</span><select name="status" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none">{statuses.filter(s=>s!=='all').map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label><span className="mb-2 block text-sm font-extrabold">الموعد</span><input name="deadline" type="date" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none"/></label><label><span className="mb-2 block text-sm font-extrabold">الميزانية</span><input name="budget" type="number" min="0" step="0.01" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none"/></label><label><span className="mb-2 block text-sm font-extrabold">العملة</span><select name="currency" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none"><option>USD</option><option>IQD</option><option>EUR</option><option>AED</option></select></label><label className="md:col-span-2"><span className="mb-2 block text-sm font-extrabold">الوصف</span><textarea name="description" rows={4} className="w-full rounded-xl border border-slate-200 bg-slate-50 p-3 outline-none"/></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">إلغاء</button><button className="btn-primary">إنشاء المشروع</button></div></form></div>}
  </div>
}
