'use client'

import { useEffect, useState } from 'react'
import { BarChart3, BriefcaseBusiness, CircleDollarSign, Target, Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

export default function AnalyticsPage(){
  const [data,setData]=useState({leads:0,won:0,projects:0,completed:0,team:0,revenue:0,invoiced:0})
  const [error,setError]=useState('')
  useEffect(()=>{(async()=>{const sb=createClient();const [leads,won,projects,completed,team,invoices]=await Promise.all([sb.from('leads').select('*',{count:'exact',head:true}),sb.from('leads').select('*',{count:'exact',head:true}).in('status',['paid','delivered']),sb.from('projects').select('*',{count:'exact',head:true}),sb.from('projects').select('*',{count:'exact',head:true}).eq('status','completed'),sb.from('profiles').select('*',{count:'exact',head:true}).eq('active',true),sb.from('invoices').select('total,amount_paid')]);const err=leads.error||won.error||projects.error||completed.error||team.error||invoices.error;if(err)return setError(err.message);const inv=invoices.data||[];setData({leads:leads.count||0,won:won.count||0,projects:projects.count||0,completed:completed.count||0,team:team.count||0,revenue:inv.reduce((s:any,r:any)=>s+Number(r.amount_paid||0),0),invoiced:inv.reduce((s:any,r:any)=>s+Number(r.total||0),0)})})()},[])
  const conversion=data.leads?Math.round((data.won/data.leads)*100):0,completion=data.projects?Math.round((data.completed/data.projects)*100):0,collection=data.invoiced?Math.round((data.revenue/data.invoiced)*100):0
  return <div className="mx-auto max-w-[1500px] space-y-5"><section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-card md:p-8"><div className="flex items-start justify-between"><div><div className="eyebrow">ANALYTICS</div><h2 className="mt-5 text-3xl font-black md:text-4xl">مؤشرات NEXORA</h2><p className="mt-3 text-sm leading-7 text-slate-500">ملخص أولي مشتق من بيانات CRM والمشاريع والفواتير والفريق الحالية.</p></div><div className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-[#0071e3]"><BarChart3 size={24}/></div></div></section>{error&&<div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Target} value={`${conversion}%`} label="Lead conversion"/><Metric icon={BriefcaseBusiness} value={`${completion}%`} label="Project completion"/><Metric icon={CircleDollarSign} value={`$${data.revenue.toLocaleString()}`} label="Collected revenue"/><Metric icon={Users} value={String(data.team)} label="Active team"/></section><section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-card"><h3 className="text-lg font-black">Operational funnel</h3><div className="mt-8 space-y-5"><Bar label="All leads" value={data.leads} max={Math.max(data.leads,1)} tone="bg-[#0071e3]"/><Bar label="Won / delivered" value={data.won} max={Math.max(data.leads,1)} tone="bg-violet-500"/><Bar label="All projects" value={data.projects} max={Math.max(data.projects,1)} tone="bg-sky-500"/><Bar label="Completed projects" value={data.completed} max={Math.max(data.projects,1)} tone="bg-emerald-500"/></div></article><article className="rounded-[28px] border border-slate-200 bg-[#07111f] p-6 text-white shadow-card"><div className="text-xs font-black tracking-[.14em] text-blue-300">CASH COLLECTION</div><strong className="mt-5 block font-[var(--font-inter)] text-5xl font-black">{collection}%</strong><p className="mt-3 text-sm leading-7 text-slate-300">من إجمالي قيمة الفواتير المسجلة تم تسجيله كـ amount paid.</p><div className="mt-8 h-3 rounded-full bg-white/10"><i style={{width:`${Math.min(100,collection)}%`}} className="block h-full rounded-full bg-blue-400"/></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/5 p-4"><span className="text-[10px] font-black text-slate-400">INVOICED</span><strong className="mt-2 block font-[var(--font-inter)]">${data.invoiced.toLocaleString()}</strong></div><div className="rounded-2xl bg-white/5 p-4"><span className="text-[10px] font-black text-slate-400">COLLECTED</span><strong className="mt-2 block font-[var(--font-inter)] text-emerald-300">${data.revenue.toLocaleString()}</strong></div></div></article></section></div>
}
function Metric({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <article className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-card"><Icon size={19} className="text-[#0071e3]"/><strong className="mt-5 block font-[var(--font-inter)] text-3xl font-black">{value}</strong><span className="mt-1 block text-xs font-bold text-slate-400">{label}</span></article>}
function Bar({label,value,max,tone}:{label:string;value:number;max:number;tone:string}){const pct=Math.max(3,Math.min(100,Math.round((value/max)*100)));return <div><div className="mb-2 flex justify-between text-xs font-black"><span>{label}</span><span className="font-[var(--font-inter)] text-slate-400">{value}</span></div><div className="h-3 rounded-full bg-slate-100"><i style={{width:`${pct}%`}} className={`block h-full rounded-full ${tone}`}/></div></div>}
