'use client'

import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Eye, EyeOff, Loader2, LockKeyhole, Mail } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

export default function ClientLoginPage(){
  const [email,setEmail]=useState('')
  const [password,setPassword]=useState('')
  const [show,setShow]=useState(false)
  const [loading,setLoading]=useState(false)
  const [message,setMessage]=useState('')

  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');try{const sb=createClient();const normalized=email.trim().toLowerCase().replace('@gmai.com','@gmail.com').replace('@gmial.com','@gmail.com');const {data,error}=await sb.auth.signInWithPassword({email:normalized,password});if(error)throw error;if(!data.user)throw new Error('لم يتم إنشاء جلسة دخول.');const {data:profile,error:pErr}=await sb.from('client_profiles').select('active').eq('id',data.user.id).maybeSingle();if(pErr)throw pErr;if(!profile?.active)throw new Error('هذا الحساب غير معتمد كبوابة عميل.');location.href='/portal'}catch(err:any){const raw=String(err?.message||err||'');setMessage(/Invalid login credentials/i.test(raw)?'البريد أو كلمة المرور غير صحيحة.':raw||'تعذر تسجيل الدخول.')}finally{setLoading(false)}}

  return <main className="grid min-h-screen place-items-center px-4 py-10"><div className="w-full max-w-5xl overflow-hidden rounded-[36px] border border-slate-200 bg-white shadow-soft"><div className="grid lg:grid-cols-2"><section className="p-7 md:p-12"><Link href="/portal" className="inline-flex items-center gap-2 text-sm font-extrabold text-slate-500"><ArrowLeft size={16}/> بوابة العملاء</Link><div className="mt-14"><div className="eyebrow">CLIENT ACCESS</div><h1 className="mt-6 text-4xl font-black tracking-[-.03em]">تسجيل دخول العميل</h1><p className="mt-4 leading-8 text-slate-500">استخدم البريد الذي تمت إضافته إلى مشروعك من فريق NEXORA.</p></div><form onSubmit={submit} className="mt-9 space-y-5"><label className="block"><span className="mb-2 block text-sm font-extrabold">البريد الإلكتروني</span><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4"><Mail size={18} className="text-slate-400"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required autoComplete="email" className="h-14 w-full bg-transparent outline-none"/></div></label><label className="block"><span className="mb-2 block text-sm font-extrabold">كلمة المرور</span><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4"><LockKeyhole size={18} className="text-slate-400"/><input value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} required minLength={8} className="h-14 w-full bg-transparent outline-none"/><button type="button" onClick={()=>setShow(v=>!v)} className="text-slate-400">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{message&&<div className="rounded-2xl border border-red-100 bg-red-50 p-3 text-sm font-bold text-red-700">{message}</div>}<button disabled={loading} className="btn-primary h-14 w-full disabled:opacity-60">{loading?<><Loader2 size={18} className="animate-spin"/> جاري التحقق…</>:'دخول البوابة'}</button></form></section><section className="relative hidden min-h-[640px] overflow-hidden bg-[#07111f] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 grid-dots opacity-20"/><div className="relative flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-xl font-black text-slate-950">N</span><span className="font-[var(--font-inter)] text-sm font-black tracking-[.2em]">NEXORA PORTAL</span></div><div className="relative"><div className="text-xs font-black tracking-[.18em] text-blue-300">YOUR PROJECT. CLEARLY.</div><h2 className="mt-5 text-5xl font-black leading-tight">Everything you need.<br/>Nothing you don’t.</h2><p className="mt-6 text-base leading-8 text-slate-300">Projects, approvals, files and updates — presented without internal operational noise.</p></div></section></div></div></main>
}
