'use client'

import { useEffect, useState } from 'react'
import { Bot, CheckCircle2, Clock3, Sparkles, TriangleAlert } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type AIRequest={id:string;user_id:string;mode:string;prompt:string;response:string|null;status:string;created_at:string;completed_at:string|null}

export default function AgentsPage(){
  const [rows,setRows]=useState<AIRequest[]>([])
  const [error,setError]=useState('')
  const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{const sb=createClient();const {data,error}=await sb.from('ai_requests').select('id,user_id,mode,prompt,response,status,created_at,completed_at').order('created_at',{ascending:false}).limit(100);if(error)setError(error.message);else setRows((data||[]) as AIRequest[]);setLoading(false)})()},[])
  return <div className="mx-auto max-w-[1500px] space-y-5"><section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-card md:p-8"><div className="flex items-start justify-between gap-6"><div><div className="eyebrow">AI WORKFORCE</div><h2 className="mt-5 text-3xl font-black md:text-4xl">AI Operations</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-500">مراقبة طلبات الذكاء الاصطناعي الحالية، حالتها ونتائجها بدون خلطها مع وظائف الإدارة الأساسية.</p></div><div className="grid h-14 w-14 place-items-center rounded-2xl bg-violet-50 text-violet-700"><Bot size={25}/></div></div></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[rows.length,'Requests',Sparkles],[rows.filter(r=>r.status==='pending').length,'Pending',Clock3],[rows.filter(r=>/complete|success/i.test(r.status)).length,'Completed',CheckCircle2],[rows.filter(r=>/error|fail/i.test(r.status)).length,'Failed',TriangleAlert]].map(([v,l,Icon]:any)=><article key={l} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-card"><Icon size={19} className="text-violet-600"/><strong className="mt-5 block font-[var(--font-inter)] text-3xl font-black">{v}</strong><span className="mt-1 block text-xs font-bold text-slate-400">{l}</span></article>)}</section>{error&&<div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}<section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card"><h3 className="text-lg font-black">آخر طلبات AI</h3><div className="mt-4 space-y-3">{loading?<div className="p-10 text-center text-sm font-bold text-slate-400">جاري التحميل…</div>:rows.length?rows.map(r=><article key={r.id} className="rounded-[22px] border border-slate-200 bg-slate-50 p-5"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div className="max-w-4xl"><div className="text-[10px] font-black tracking-[.14em] text-violet-600">{r.mode}</div><p className="mt-2 text-sm font-bold leading-7 text-slate-700">{r.prompt}</p>{r.response&&<p className="mt-3 rounded-xl bg-white p-3 text-xs leading-6 text-slate-500">{r.response}</p>}</div><span className="w-fit rounded-full bg-white px-2.5 py-1 text-[10px] font-black text-slate-600">{r.status}</span></div><span className="mt-3 block text-[10px] font-bold text-slate-400">{new Date(r.created_at).toLocaleString('ar-IQ')}</span></article>):<div className="p-10 text-center text-sm font-bold text-slate-400">لا توجد طلبات AI.</div>}</div></section></div>
}
