import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, Bot, Boxes, ChartNoAxesCombined, CheckCircle2, Cpu, Gauge, Layers3, MessageSquareMore, ShieldCheck, Sparkles, Workflow } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { ContactForm } from '@/components/contact-form'

const services=[
  {icon:Boxes,title:'Custom business systems',text:'Turn your workflow into a clear operating system for CRM, projects, staff, files, reporting and permissions.'},
  {icon:Bot,title:'AI agents',text:'AI agents for sales, research, support and analysis, with human approvals before sensitive actions.'},
  {icon:Workflow,title:'Process automation',text:'Connect forms, email, databases, CRM and external services into workflows that run automatically.'},
  {icon:Layers3,title:'Digital products & platforms',text:'Fast, mobile-first websites, SaaS products, dashboards and portals designed to scale.'},
]

export default function EnglishHome(){
  return <main dir="ltr" className="min-h-screen overflow-x-hidden font-[var(--font-inter)]">
    <SiteHeader locale="en" />
    <section className="container-shell grid min-h-[780px] items-center gap-10 py-20 lg:grid-cols-[1.02fr_.98fr] lg:py-24">
      <div><div className="eyebrow"><span className="brand-dot"/> NEXORA BUSINESS OS</div><h1 className="mt-7 max-w-[780px] text-[clamp(52px,7vw,104px)] font-black leading-[.98] tracking-[-.05em] text-slate-950">Systems that <span className="block bg-gradient-to-r from-[#0071e3] to-[#5d3fd3] bg-clip-text text-transparent">sell, operate</span> and scale with you.</h1><p className="mt-7 max-w-[700px] text-[17px] font-medium leading-8 text-slate-500 md:text-[20px]">Software, AI and automation in one connected platform. We design the customer experience and build the operating system behind it.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#contact" className="btn-primary min-w-[160px]">Start a project <ArrowUpRight size={18}/></a><Link href="/command" className="btn-secondary min-w-[160px]">Explore NEXORA Command <ArrowLeft size={18}/></Link></div><div className="mt-10 flex flex-wrap gap-6 text-sm font-bold text-slate-500"><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-500"/> Arabic / English</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-500"/> Role-based access</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-500"/> AI + Automation</span></div></div>

      <div><div className="card relative overflow-hidden p-3 md:p-5"><div className="absolute inset-0 grid-dots opacity-40"/><div className="relative rounded-[24px] border border-slate-200 bg-white p-4 shadow-soft md:p-6"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><div className="text-[10px] font-black tracking-[.18em] text-[#0071e3]">NEXORA COMMAND</div><h2 className="mt-1 text-lg font-extrabold">Executive Overview</h2></div><div className="flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-[11px] font-extrabold text-emerald-700"><span className="brand-dot !h-2 !w-2"/> Live</div></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{[['24','Leads'],['12','Projects'],['36','Automations'],['8','Team']].map(([n,l])=><div className="metric-tile" key={l}><strong className="text-3xl font-black">{n}</strong><span className="mt-2 block text-xs font-bold text-slate-400">{l}</span></div>)}</div><div className="mt-3 grid gap-3 md:grid-cols-[1.35fr_.65fr]"><div className="metric-tile min-h-[260px]"><div className="flex items-center justify-between"><span className="text-sm font-extrabold">Lead pipeline</span><ChartNoAxesCombined size={18} className="text-[#0071e3]"/></div><div className="mt-8 flex h-36 items-end gap-2">{[44,72,58,88,64,48,76].map((h,i)=><i key={i} style={{height:`${h}%`}} className="flex-1 rounded-t-lg bg-gradient-to-t from-[#0071e3] to-[#72b7ff]"/>)}</div><div className="mt-5 flex justify-between text-[11px] font-bold text-slate-400"><span>New</span><span>Qualified</span><span>Proposal</span><span>Won</span></div></div><div className="space-y-3"><div className="metric-tile"><Sparkles size={18} className="text-violet-600"/><b className="mt-5 block text-sm">AI Assistant</b><p className="mt-1 text-xs leading-6 text-slate-400">Actions ready for review.</p></div><div className="metric-tile"><ShieldCheck size={18} className="text-emerald-600"/><b className="mt-5 block text-sm">System Health</b><p className="mt-1 text-xs leading-6 text-slate-400">Core services healthy.</p></div></div></div></div></div></div>
    </section>

    <section id="services" className="container-shell py-24 md:py-32"><div className="max-w-3xl"><div className="eyebrow">WHAT WE BUILD</div><h2 className="mt-6 text-[clamp(38px,5vw,70px)] font-black leading-[1.06] tracking-[-.04em]">Not just a website. A connected operating layer for your business.</h2><p className="mt-5 text-lg leading-8 text-slate-500">A polished customer experience, an organized workspace for your team, and clear data for management.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{services.map(({icon:Icon,title,text})=><article key={title} className="card min-h-[280px] p-7 md:p-9"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-[#0071e3]"><Icon size={23}/></div><h3 className="mt-12 text-2xl font-black">{title}</h3><p className="mt-4 max-w-xl text-[15px] font-medium leading-7 text-slate-500">{text}</p></article>)}</div></section>

    <section id="platform" className="container-shell py-24 md:py-32"><div className="card overflow-hidden p-8 md:p-12 lg:p-16"><div className="grid items-center gap-12 lg:grid-cols-2"><div><div className="eyebrow">ONE CONNECTED SYSTEM</div><h2 className="mt-6 text-[clamp(40px,5vw,72px)] font-black leading-[1.03] tracking-[-.04em]">Everything connected. Less tool chaos.</h2><p className="mt-6 text-lg leading-8 text-slate-500">Website → Leads → AI → Automation → Projects → Analytics. One platform connecting the customer journey with internal operations.</p></div><div className="grid gap-3 sm:grid-cols-2">{[['CRM',Gauge],['AI Workforce',Cpu],['Approvals',ShieldCheck],['Client Portal',MessageSquareMore]].map(([label,Icon]:any)=><div key={label} className="metric-tile flex min-h-[140px] flex-col justify-between"><Icon size={22} className="text-[#0071e3]"/><b className="text-lg">{label}</b></div>)}</div></div></div></section>

    <section id="process" className="container-shell py-24 md:py-32"><div className="max-w-3xl"><div className="eyebrow">PROCESS</div><h2 className="mt-6 text-[clamp(38px,5vw,66px)] font-black tracking-[-.04em]">From idea to a system ready to scale.</h2></div><div className="mt-12 grid gap-3 md:grid-cols-4">{[['01','Discover'],['02','Design'],['03','Build'],['04','Scale']].map(([n,t])=><div key={n} className="card min-h-[210px] p-7"><span className="text-xs font-black text-[#0071e3]">{n}</span><h3 className="mt-20 text-2xl font-black">{t}</h3></div>)}</div></section>

    <section id="contact" className="container-shell pb-28 pt-20"><div className="rounded-[36px] bg-[#07111f] p-6 text-white shadow-soft md:p-10 lg:p-12"><div className="grid gap-10 lg:grid-cols-[.88fr_1.12fr] lg:items-start"><div className="lg:sticky lg:top-28"><div className="text-xs font-black tracking-[.18em] text-blue-300">READY TO BUILD?</div><h2 className="mt-5 max-w-4xl text-[clamp(40px,5vw,72px)] font-black leading-[1.03] tracking-[-.04em]">Ready to build what’s next?</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Tell us what you want to build, automate or improve. Your request goes directly into NEXORA CRM for structured follow-up.</p><div className="mt-8 space-y-3 text-sm font-bold text-slate-300"><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-400"/> Direct CRM intake</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-400"/> Human approval before sensitive actions</span><span className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-400"/> No passwords or secret keys requested</span></div></div><ContactForm locale="en"/></div></div></section>

    <footer className="container-shell flex flex-col gap-4 border-t border-slate-200 py-8 text-sm font-semibold text-slate-400 md:flex-row md:items-center md:justify-between"><span>NEXORA AI © 2026</span><span>Software • AI • Automation</span></footer>
  </main>
}
