'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { CalendarClock, CheckCircle2, CircleDot, Clock3, Plus, Search, X } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Task={id:string;title:string;description:string|null;status:string;priority:string;due_at:string|null;project_id:string|null;assigned_to:string|null;created_at:string}
const statuses=['all','todo','in_progress','review','done','cancelled']
const labels:Record<string,string>={all:'كل الحالات',todo:'To Do',in_progress:'In Progress',review:'Review',done:'Done',cancelled:'Cancelled'}

export default function TasksPage(){
  const [rows,setRows]=useState<Task[]>([])
  const [query,setQuery]=useState('')
  const [status,setStatus]=useState('all')
  const [open,setOpen]=useState(false)
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')

  async function load(){setLoading(true);const sb=createClient();let q=sb.from('tasks').select('id,title,description,status,priority,due_at,project_id,assigned_to,created_at').order('created_at',{ascending:false}).limit(300);if(status!=='all')q=q.eq('status',status);const {data,error}=await q;if(error)setError(error.message);else{setRows((data||[]) as Task[]);setError('')}setLoading(false)}
  useEffect(()=>{load()},[status])
  const filtered=useMemo(()=>{const n=query.trim().toLowerCase();if(!n)return rows;return rows.filter(r=>[r.title,r.description,r.status,r.priority].some(v=>String(v||'').toLowerCase().includes(n)))},[rows,query])

  async function createTask(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const sb=createClient();const {data:{user}}=await sb.auth.getUser();const payload={title:String(fd.get('title')||'').trim(),description:String(fd.get('description')||'').trim()||null,status:String(fd.get('status')||'todo'),priority:String(fd.get('priority')||'normal'),due_at:String(fd.get('due_at')||'')||null,created_by:user?.id||null};const {error}=await sb.from('tasks').insert(payload);if(error)return setError(error.message);setOpen(false);await load()}
  async function changeStatus(task:Task,next:string){const sb=createClient();const {error}=await sb.from('tasks').update({status:next}).eq('id',task.id);if(error)return setError(error.message);await load()}

  return <div className="mx-auto max-w-[1500px] space-y-5">
    <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-card md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow">TASK MANAGEMENT</div><h2 className="mt-5 text-3xl font-black md:text-4xl">المهام</h2><p className="mt-3 text-sm leading-7 text-slate-500">إدارة المهام الحقيقية من جدول tasks، مع تحديث الحالة مباشرة.</p></div><button onClick={()=>setOpen(true)} className="btn-primary"><Plus size={17}/> مهمة جديدة</button></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[rows.filter(r=>r.status==='todo').length,'To Do',CircleDot],[rows.filter(r=>r.status==='in_progress').length,'In Progress',Clock3],[rows.filter(r=>r.status==='review').length,'Review',CalendarClock],[rows.filter(r=>r.status==='done').length,'Done',CheckCircle2]].map(([v,l,Icon]:any)=><article key={l} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-card"><Icon size={19} className="text-[#0071e3]"/><strong className="mt-5 block font-[var(--font-inter)] text-3xl font-black">{v}</strong><span className="mt-1 block text-xs font-bold text-slate-400">{l}</span></article>)}</section>
    <section className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-card"><div className="flex flex-col gap-3 md:flex-row"><div className="flex flex-1 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4"><Search size={17} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-11 w-full bg-transparent outline-none" placeholder="بحث في المهام…"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold outline-none">{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div></section>
    {error&&<div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
    <section className="grid gap-4 lg:grid-cols-3">{['todo','in_progress','review'].map(col=><div key={col} className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-card"><div className="flex items-center justify-between px-1"><h3 className="font-black">{labels[col]}</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-black text-slate-500">{filtered.filter(r=>r.status===col).length}</span></div><div className="mt-4 space-y-3">{loading?<div className="p-5 text-center text-xs font-bold text-slate-400">Loading…</div>:filtered.filter(r=>r.status===col).map(t=><article key={t.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><strong className="text-sm leading-6">{t.title}</strong><span className={`rounded-full px-2 py-1 text-[10px] font-black ${t.priority==='urgent'?'bg-red-50 text-red-700':t.priority==='high'?'bg-amber-50 text-amber-700':'bg-white text-slate-500'}`}>{t.priority}</span></div><p className="mt-2 line-clamp-2 text-xs leading-6 text-slate-400">{t.description||'بدون وصف'}</p><div className="mt-4 flex items-center justify-between"><span className="text-[10px] font-bold text-slate-400">{t.due_at?new Date(t.due_at).toLocaleString('ar-IQ'):'بدون موعد'}</span><select value={t.status} onChange={e=>changeStatus(t,e.target.value)} className="h-8 rounded-lg border border-slate-200 bg-white px-2 text-[10px] font-black outline-none">{statuses.filter(s=>s!=='all').map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div></article>)}</div></div>)}</section>
    {filtered.filter(r=>r.status==='done').length>0&&<section className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-card"><h3 className="font-black">المهام المكتملة</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.filter(r=>r.status==='done').map(t=><div key={t.id} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><strong className="text-sm text-emerald-900">{t.title}</strong></div>)}</div></section>}
    {open&&<div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/25 p-4 backdrop-blur-sm"><form onSubmit={createTask} className="w-full max-w-2xl rounded-[30px] border border-slate-200 bg-white p-6 shadow-soft md:p-8"><div className="flex items-start justify-between"><div><div className="eyebrow">NEW TASK</div><h3 className="mt-4 text-2xl font-black">إنشاء مهمة</h3></div><button type="button" onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><X size={18}/></button></div><div className="mt-7 grid gap-4 md:grid-cols-2"><label className="md:col-span-2"><span className="mb-2 block text-sm font-extrabold">عنوان المهمة</span><input name="title" required className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none"/></label><label><span className="mb-2 block text-sm font-extrabold">الحالة</span><select name="status" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none">{statuses.filter(s=>s!=='all').map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label><span className="mb-2 block text-sm font-extrabold">الأولوية</span><select name="priority" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="md:col-span-2"><span className="mb-2 block text-sm font-extrabold">الموعد</span><input name="due_at" type="datetime-local" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none"/></label><label className="md:col-span-2"><span className="mb-2 block text-sm font-extrabold">الوصف</span><textarea name="description" rows={4} className="w-full rounded-xl border border-slate-200 bg-slate-50 p-3 outline-none"/></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="btn-secondary">إلغاء</button><button className="btn-primary">إنشاء المهمة</button></div></form></div>}
  </div>
}
