'use client'

import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, PauseCircle, PlayCircle, Workflow } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Run={id:string;lead_id:string;run_version:number;status:string;error_message:string|null;started_at:string;completed_at:string|null;created_at:string}
type Settings={id:number;enabled:boolean;auto_prepare_new_leads:boolean;minimum_lead_score:number;default_currency:string;require_owner_approval:boolean;updated_at:string}

export default function AutomationsPage(){
  const [runs,setRuns]=useState<Run[]>([])
  const [settings,setSettings]=useState<Settings|null>(null)
  const [error,setError]=useState('')
  const [busy,setBusy]=useState(false)

  async function load(){const sb=createClient();const [r,s]=await Promise.all([sb.from('autopilot_runs').select('id,lead_id,run_version,status,error_message,started_at,completed_at,created_at').order('created_at',{ascending:false}).limit(100),sb.from('autopilot_settings').select('id,enabled,auto_prepare_new_leads,minimum_lead_score,default_currency,require_owner_approval,updated_at').eq('id',1).maybeSingle()]);if(r.error||s.error)setError(r.error?.message||s.error?.message||'');else{setRuns((r.data||[]) as Run[]);setSettings(s.data as Settings|null);setError('')}}
  useEffect(()=>{load()},[])
  async function patch(patch:Partial<Settings>){if(!settings)return;setBusy(true);const sb=createClient();const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from('autopilot_settings').update({...patch,updated_by:user?.id||null}).eq('id',settings.id);setBusy(false);if(error)return setError(error.message);await load()}

  return <div className="mx-auto max-w-[1500px] space-y-5"><section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-card md:p-8"><div className="flex items-start justify-between gap-6"><div><div className="eyebrow">AUTOMATION CENTER</div><h2 className="mt-5 text-3xl font-black md:text-4xl">الأتمتة وAutopilot</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-500">التحكم بإعدادات الـAutopilot ومراقبة التنفيذات والأخطاء من الجداول الحالية.</p></div><div className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-[#0071e3]"><Workflow size={24}/></div></div></section>{error&&<div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{settings&&<section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Toggle title="Autopilot" text="التشغيل العام" value={settings.enabled} onChange={v=>patch({enabled:v})}/><Toggle title="Auto Prepare" text="تجهيز الـLeads الجديدة" value={settings.auto_prepare_new_leads} onChange={v=>patch({auto_prepare_new_leads:v})}/><Toggle title="Owner Approval" text="يتطلب موافقة المالك" value={settings.require_owner_approval} onChange={v=>patch({require_owner_approval:v})}/><article className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-card"><span className="text-xs font-black text-slate-400">MIN LEAD SCORE</span><input disabled={busy} type="number" min="0" max="100" value={settings.minimum_lead_score} onChange={e=>setSettings({...settings,minimum_lead_score:Number(e.target.value)})} onBlur={e=>patch({minimum_lead_score:Number(e.target.value)})} className="mt-4 h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 font-[var(--font-inter)] text-xl font-black outline-none"/></article></section>}<section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-center justify-between"><h3 className="text-lg font-black">آخر التنفيذات</h3><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-500">{runs.length}</span></div><div className="mt-4 divide-y divide-slate-100">{runs.length?runs.map(r=><div key={r.id} className="grid gap-3 py-4 md:grid-cols-[1.2fr_.7fr_.7fr_1fr] md:items-center"><div><strong className="block text-sm">Lead {r.lead_id.slice(0,8)}…</strong><span className="mt-1 block text-xs font-bold text-slate-400">Run v{r.run_version}</span></div><RunStatus status={r.status}/><span className="text-xs font-bold text-slate-400">{new Date(r.started_at).toLocaleString('ar-IQ')}</span><span className={`text-xs font-bold ${r.error_message?'text-red-600':'text-slate-400'}`}>{r.error_message||'No error'}</span></div>):<div className="p-10 text-center text-sm font-bold text-slate-400">لا توجد تنفيذات بعد.</div>}</div></section></div>
}

function Toggle({title,text,value,onChange}:{title:string;text:string;value:boolean;onChange:(v:boolean)=>void}){return <article className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-start justify-between"><div><span className="text-xs font-black text-slate-400">{title}</span><strong className="mt-3 block text-lg">{value?'Active':'Paused'}</strong><p className="mt-1 text-xs font-bold text-slate-400">{text}</p></div><button onClick={()=>onChange(!value)} className={`grid h-11 w-11 place-items-center rounded-xl ${value?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{value?<PlayCircle size={20}/>:<PauseCircle size={20}/>}</button></div></article>}
function RunStatus({status}:{status:string}){const ok=/complete|success|ready/i.test(status),bad=/error|fail/i.test(status);return <span className={`inline-flex w-fit items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-black ${bad?'bg-red-50 text-red-700':ok?'bg-emerald-50 text-emerald-700':'bg-blue-50 text-blue-700'}`}>{bad?<AlertTriangle size={12}/>:ok?<CheckCircle2 size={12}/>:<PlayCircle size={12}/>} {status}</span>}
